# Use the official Ruby image as the base image
FROM ruby:alpine3.17

# Set the working directory in the container
WORKDIR /app

# Copy the Gemfile and Gemfile.lock to the container
COPY Gemfile Gemfile.lock ./

# Install the Ruby dependencies
RUN bundle install

# Copy the rest of the application code to the container
COPY . .

# Set the command to run the rails server
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]